apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.8.0.2:6443
    token: "akel57.520pp5ikvglq80fx"
    caCertHashes:
    - "sha256:8fa7b5e556af1024a4b6969010c610f80c6cca242d387091dfa3c380e1e3e2a3"
nodeRegistration:
  kubeletExtraArgs:
  - name: "node-ip"
    value: "10.8.1.2,fc00:0:0800:1::2"