---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchExpressions:
    - key: kubernetes.io/hostname
      operator: In
      values:
      - london-vm-00
      - london-vm-01
      - london-vm-02
  bgpInstances:
  - name: "asn65000"
    localASN: 65000
    peers:
    - name: "paris-rr"
      peerASN: 65000
      peerAddress: fc00:0:5555::1
      peerConfigRef:
        name: "cilium-peer"
    - name: "barcelona-rr"
      peerASN: 65000
      peerAddress: fc00:0:6666::1
      peerConfigRef:
        name: "cilium-peer"
    vrfs:
    - vrfRef: "carrots"
      rd: "9:9"
      importRTs:
        - "9:9"
      exportRTs:
        - "9:9"
      configRef: carrots-config

---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  families:
    - afi: ipv6
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgpv6unicast"
    - afi: ipv4
      safi: mpls_vpn

---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPNodeConfigOverride
metadata:
  name: london-vm-00
spec:
  bgpInstances:
    - name: "asn65000"
      srv6Responder: true
      peers:
        - name: "paris-rr"
          localAddress: fc00:0:800::2
        - name: "barcelona-rr"
          localAddress: fc00:0:800::2

---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPNodeConfigOverride
metadata:
  name: london-vm-01
spec:
  bgpInstances:
    - name: "asn65000"
      srv6Responder: true
      peers:
        - name: "paris-rr"
          localAddress: fc00:0:800:1::2
        - name: "barcelona-rr"
          localAddress: fc00:0:800:1::2

---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPNodeConfigOverride
metadata:
  name: london-vm-02
spec:
  bgpInstances:
    - name: "asn65000"
      srv6Responder: true
      peers:
        - name: "paris-rr"
          localAddress: fc00:0:800:2::2
        - name: "barcelona-rr"
          localAddress: fc00:0:800:2::2

---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPAdvertisement
metadata:
  name: bgp-ipv6-unicast
  labels:
    advertise: bgpv6unicast
spec:
  advertisements:
    - advertisementType: "SRv6LocatorPool"
      selector:
        matchLabels:
          export: "pool0"
    - advertisementType: "PodCIDR"