flowchart TD
    UbuntuVM["🐧 Ubuntu VM (Containerlab)"]  --> ManagementNetwork["☁️ fa:fa-code  Management"]
    WindowsVM["💻 Windows VM (Lab Instructions, RDP  & Terminal)"]  --> ManagementNetwork["☁️ fa:fa-code Management"]


%% Individual node styling. 

    style ManagementNetwork color:#FFFFFF, fill:#AA00FF, stroke:#AA00FF
    style UbuntuVM color:#FFFFFF, stroke:#00C853, fill:#00C853
    style WindowsVM color:#FFFFFF, stroke:#2962FF, fill:#2962FF
